spring.application.name=OuroEssence
paypal.client.id=${PAYPAL_CLIENT_ID:ASP30i2roNa8OoPp95_mCk5u0-pCBgyG2eXXQW1wMwiCBmBkmAuddfXLOjRqf3JQV8aMluGnBD_JYFxW}
paypal.client.secret=${PAYPAL_CLIENT_SECRET:EFUwYfD8mjmk8m2wCqyYsd5ZZUFJevVTJHwaDJ-9fI5Sz7CG_NixzQgURzH1CHz0Hb3pyyqDDF14hZjz}
paypal.mode=${PAYPAL_MODE:sandbox}